name: Devsecops-pipeline


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11


      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Run Safety dependency scan
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: safety scan -r requirements.txt

      - name: Run Bandit SAST scan
        run: bandit -r app.py --exit-zero

      - name: Run tests
        run: pytest test_app.py -v

      - name: Start Flask and wait
        run: python3 app.py & sleep 5

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://127.0.0.1:5000/login'
          cmd_options: '-a'

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: Scan_Records
          path: report*
